Repository apiato/apiato, pull requests merged in 2024-08, with the labels that each got.

#766 fix: incorrect docblock
  app/Containers/AppSection/Authentication/UI/API/Controllers/LoginProxyForWebClientController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/RefreshProxyForWebClientController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/RegisterUserController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/ResetPasswordController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/SendVerificationEmailController.php
  app/Containers/AppSection/Authorization/Data/Migrations/2016_12_29_201047_create_permission_tables.php
  app/Containers/AppSection/Authorization/Data/Migrations/2017_04_22_122453_add_extra_fields_to_permissions_tale.php
  app/Containers/AppSection/Authorization/Data/Migrations/2017_04_22_122522_add_extra_fields_to_roles_table.php
  app/Containers/AppSection/Authorization/Models/Permission.php
  app/Containers/AppSection/Authorization/Models/Role.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/AssignRolesToUserController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/CreateRoleController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/DeleteRoleController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/FindPermissionByIdController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/FindRoleByIdController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/GivePermissionsToRoleController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/GivePermissionsToUserController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListPermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListRolePermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListUserPermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListUserRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/RemoveUserRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/RevokeRolePermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/RevokeUserPermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/SyncRolePermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/SyncUserRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Requests/RevokeUserPermissionsRequest.php
  app/Containers/AppSection/Authorization/UI/API/Transformers/PermissionAdminTransformer.php
  app/Containers/AppSection/User/Data/Migrations/2000_01_01_000001_create_users_table.php
  app/Containers/AppSection/User/Data/Migrations/2000_01_01_000002_create_password_reset_tokens_table.php
  app/Containers/AppSection/User/UI/API/Controllers/DeleteUserController.php
  app/Containers/AppSection/User/UI/API/Controllers/FindUserByIdController.php
  app/Containers/AppSection/User/UI/API/Controllers/GetUserProfileController.php
  app/Containers/AppSection/User/UI/API/Controllers/ListUsersController.php
  app/Containers/AppSection/User/UI/API/Controllers/UpdatePasswordController.php
  app/Containers/AppSection/User/UI/API/Controllers/UpdateUserController.php
  app/Ship/Configs/fractal.php
  app/Ship/Migrations/2017_09_12_174826_create_notifications_table.php
  app/Ship/Migrations/2019_08_19_000000_create_failed_jobs_table.php
  app/Ship/Migrations/2021_03_01_150940_create_jobs_table.php
  app/Ship/Migrations/2024_05_31_160702_create_test_users_table.php
  app/Ship/Parents/Repositories/Repository.php
  app/Ship/Tests/Unit/Configs/FractalConfigTest.php
Labels: type: fix

#759 Update documentation links
  README.md
Labels: type: documentation, type: fix

#769 feat(controller): revert response facade usage
  app/Containers/AppSection/Authentication/UI/API/Controllers/ForgotPasswordController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/LoginProxyForWebClientController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/RefreshProxyForWebClientController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/RegisterUserController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/ResetPasswordController.php
  app/Containers/AppSection/Authentication/UI/API/Controllers/SendVerificationEmailController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/AssignRolesToUserController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/CreateRoleController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/DeleteRoleController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/FindPermissionByIdController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/FindRoleByIdController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/GivePermissionsToRoleController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/GivePermissionsToUserController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListPermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListRolePermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListUserPermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/ListUserRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/RemoveUserRolesController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/RevokeRolePermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/RevokeUserPermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/SyncRolePermissionsController.php
  app/Containers/AppSection/Authorization/UI/API/Controllers/SyncUserRolesController.php
  app/Containers/AppSection/User/UI/API/Controllers/DeleteUserController.php
  app/Containers/AppSection/User/UI/API/Controllers/FindUserByIdController.php
  app/Containers/AppSection/User/UI/API/Controllers/GetUserProfileController.php
  app/Containers/AppSection/User/UI/API/Controllers/ListUsersController.php
  app/Containers/AppSection/User/UI/API/Controllers/UpdatePasswordController.php
  app/Containers/AppSection/User/UI/API/Controllers/UpdateUserController.php
  app/Ship/Configs/apiato.php
  app/Ship/Tests/Unit/Configs/ApiatoConfigTest.php
Labels: type: refactor
